 "use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Globe2, LockKeyhole } from "lucide-react";
import { api, AuthState, ApiError } from "@/lib/auth";
export default function Login() {
 const router=useRouter(); const [mode,setMode]=useState<"login"|"register">("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api<AuthState>("/auth/me").then(()=>{if(active)router.replace("/dashboard");}).catch(()=>{});return()=>{active=false;};},[router]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{if(mode==="register"){await api("/auth/register",{method:"POST",body:JSON.stringify({email,password})});}await api<AuthState>("/auth/login",{method:"POST",body:JSON.stringify({email,password})});router.replace("/dashboard");}catch(err){setError(err instanceof ApiError && err.status===401 ? "Invalid credentials or expired session." : err instanceof Error?err.message:"Unable to sign in");}finally{setBusy(false);}}
 return <main className="auth-page"><section className="auth-story"><div className="brand"><span className="brand-mark"><Globe2 size={23}/></span> WAAXALMA</div><div className="story-content"><span className="eyebrow">LANGUAGE WITHOUT BORDERS</span><h1>Every voice.<br/><em>Every language.</em><br/>One connection.</h1><p>Translate, interpret, and connect through a single AI-powered language workspace.</p><div className="story-line"><span/> Speech recognition · Translation · Voice synthesis</div></div><div className="story-footer">Built for conversations that matter.</div></section><section className="auth-form-area"><div className="auth-card"><span className="eyebrow">WELCOME TO WAAXALMA</span><h2>{mode==="login"?"Sign in to your workspace":"Create your account"}</h2><p className="muted">Access your personal language intelligence dashboard.</p><form onSubmit={submit}><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label htmlFor="password">Password</label><input id="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} minLength={mode==="register"?12:1} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"} <ArrowRight size={18}/></button></form><p className="switch">{mode==="login"?"New to Waaxalma?":"Already have an account?"} <button onClick={()=>{setError("");setMode(mode==="login"?"register":"login");}}>{mode==="login"?"Create an account":"Sign in"}</button></p><div className="secure"><LockKeyhole size={15}/> Secure, private workspace</div></div></section></main>;
}
