from enum import Enum


class ErrorCode(str, Enum):
    # Request and session errors
    INVALID_INPUT = "INVALID_INPUT"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"

    # Audio validation errors
    INVALID_AUDIO = "INVALID_AUDIO"
    EMPTY_AUDIO = "EMPTY_AUDIO"
    UNSUPPORTED_AUDIO_FORMAT = "UNSUPPORTED_AUDIO_FORMAT"
    UNSUPPORTED_AUDIO_MIME_TYPE = "UNSUPPORTED_AUDIO_MIME_TYPE"
    AUDIO_TYPE_MISMATCH = "AUDIO_TYPE_MISMATCH"
    AUDIO_TOO_LARGE = "AUDIO_TOO_LARGE"
    AUDIO_TOO_LONG = "AUDIO_TOO_LONG"
    CORRUPTED_AUDIO = "CORRUPTED_AUDIO"

    # Agent execution errors
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    AGENT_TIMEOUT = "AGENT_TIMEOUT"
    AGENT_EXECUTION_FAILED = "AGENT_EXECUTION_FAILED"
    INVALID_AGENT_RESULT = "INVALID_AGENT_RESULT"

    # Provider errors
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"

    # Pipeline errors
    PIPELINE_ERROR = "PIPELINE_ERROR"